project:
  type: website
  output-dir: _site

website:
  title: "Jared Black"
  site-url: "https://black-jl.github.io/econvita"
  navbar:
    pinned: true
    left:
      - text: "home"
        href: index.qmd
      - text: "research"
        href: research.qmd
      - text: "cv"
        href: cv.pdf
        target: _blank
      - text: "teaching"
        href: teaching.qmd
    right:
      - text: "email"
        href: mailto:jared_black@baylor.edu
      - icon: github
        href: https://github.com/Black-JL
        aria-label: GitHub
      - icon: linkedin
        href: https://www.linkedin.com/in/jared-black-a1420a32/
        aria-label: LinkedIn
      - text: "substack"
        href: https://substack.com/@jlblack

format:
  html:
    theme: theme.scss
    toc: false
    page-layout: full
    smooth-scroll: true
